apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
    tier: web
spec:
  type: NodePort
  selector:
    app: app
    tier: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30008