apiVersion: v1
kind: Service
metadata:
  name: bdd-service
  labels:
    app: bdd
    tier: data
spec:
  type: NodePort
  selector:
    app: bdd
    tier: data
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30009